PREFIX=/usr/local

SBINDIR=$(PREFIX)/sbin
PLUGINDIR=$(PREFIX)/libexec

INSTALL_PREFIX=$(DETSDIR)$(PREFIX)
INSTALL_SBINDIR=$(DETSDIR)$(SBINDIR)
INSTALL_PLUGINDIR=$(DETSDIR)$(PLUGINDIR)

CFLAGS=-DPLUGINDIR=\"$(PLUGINDIR)\"
